package Enums;

public enum RequestType {
    LOGIN, CREATE_ACCOUNT, CREATE_STORE, CREATE_PRODUCT, EDIT_PRODUCT, DELETE_PRODUCT, VIEW_PRODUCTS, VIEW_STATISTICS,
    EXPORT_PRODUCTS, VIEW_ITEMS_IN_CARTS, SAVE_AND_QUIT, VIEW_MARKET, SEARCH, EXPORT_PURCHASES, VIEW_CART,
    DELETE_ACCOUNT, ADD_TO_CART, BUY_PRODUCT, SORT_PRICE, EDIT_NAME, EDIT_STORE, EDIT_DESCRIPTION, EDIT_QUANTITY, EDIT_PRICE, SORT_QUANTITY
}
